baseURL = "https://shijianxu.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alexis Tacnet"
title = "DarthXSJ"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "DarthXSJ's Homepage"
copyright = "Copyright © 2022 DarthXSJ"
logofile = "img/logo2.PNG"
faviconfile = "img/logo2.PNG"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "shijianxu"
google-scholar = "4szy6p8AAAAJ"
email = "shijian.xu@epfl.ch"
linkedin = "john-example-aa80ue8è"
twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
googleanalytics = "UA-129122942-1"